# Generated by Django 4.0.4 on 2022-05-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
