# Generated by Django 4.0.4 on 2022-05-02 23:55

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(10), djmoney.models.validators.MaxMoneyValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(20), djmoney.models.validators.MaxMoneyValidator(100000)]),
        ),
    ]
