# Generated by Django 4.0.4 on 2022-05-19 09:11

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_deposit_amount_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
